[package]
name = "nyjako_os"
version = "0.1.0"
edition = "2021"
authors = [
    "Kacper Tucholski <kacper.tucholski.kt@gmail.com>"
]

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"

[[test]]
name = "should_panic"
harness = false

[package.metadata.bootimage]
test-args = ["-device", "isa-debug-exit,iobase=0xf4,iosize=0x04", "-serial", "stdio", "-display", "none"]
test-success-exit-code = 33   # (0x10 << 1) | 1
test-timeout = 30             # (in seconds) for now 30s should be enagh enough for everybody might need to be increased later

[dependencies]
bootloader = "0.9"
volatile = "0.2.6"
lazy_static = {version = "1.5.0", features = ["spin_no_std"]}
spin = "0.5.2"
x86_64 = "0.14.2"
uart_16550 = "0.2.0"